{
	"version": 1708147678,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/player-sheet3.png",
		"images/player-sheet4.png",
		"images/player-sheet5.png",
		"images/ground.png",
		"images/tile-sheet0.png",
		"images/tile-sheet1.png",
		"images/tile-sheet2.png",
		"images/camera-sheet0.png",
		"images/background-sheet0.png",
		"images/sprite-sheet0.png",
		"images/batasbawah-sheet0.png",
		"images/obstacle-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite22-sheet1.png",
		"images/sprite22-sheet2.png",
		"images/sprite22-sheet3.png",
		"images/sprite22-sheet4.png",
		"images/sprite22-sheet5.png",
		"images/sprite23-sheet0.png",
		"images/bgggggg-sheet0.png",
		"images/sprite25-sheet0.png",
		"images/sprite26-sheet0.png",
		"images/sprite27-sheet0.png",
		"images/sprite28-sheet0.png",
		"images/d9702cc954204eefa33bf9ff-sheet0.png",
		"images/sprite29-sheet0.png",
		"images/sprite24-sheet0.png",
		"images/sprite30-sheet0.png",
		"images/sprite32-sheet0.png",
		"images/sprite33-sheet0.png",
		"images/sprite34-sheet0.png",
		"images/sprite35-sheet0.png",
		"images/sprite36-sheet0.png",
		"images/sprite37-sheet0.png",
		"images/sprite38-sheet0.png",
		"images/sprite39-sheet0.png",
		"images/sprite40-sheet0.png",
		"images/sprite44-sheet0.png",
		"images/sprite45-sheet0.png",
		"images/sprite47-sheet0.png",
		"images/sprite48-sheet0.png",
		"images/sprite50-sheet0.png",
		"images/sprite54-sheet0.png",
		"images/sprite55-sheet0.png",
		"images/sprite56-sheet0.png",
		"images/sprite57-sheet0.png",
		"images/sprite59-sheet0.png",
		"images/sprite60-sheet0.png",
		"images/sprite62-sheet0.png",
		"images/sprite65-sheet0.png",
		"images/sprite66-sheet0.png",
		"images/sprite72-sheet0.png",
		"media/sound main.ogg",
		"media/opening dan seting.ogg",
		"media/wortel.ogg",
		"media/wortel 2.ogg",
		"media/bom.ogg",
		"media/wortel baru.ogg",
		"media/ambil wortel.ogg",
		"media/wortelllllll.ogg",
		"media/makan wrtl.ogg",
		"media/mkn.ogg",
		"media/mixkit-delightful-4.ogg",
		"media/y2meta.app - super smash bros ultimate vctory sound effect (128 kbps).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}