{
	"version": 1708136720,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/player-sheet3.png",
		"images/ground.png",
		"images/camera-sheet0.png",
		"images/bg.png",
		"images/lifeobject-sheet0.png",
		"images/obstacle-sheet0.png",
		"images/coin-sheet0.png",
		"images/loadingscreen-sheet0.png",
		"images/loadingbg-sheet0.png",
		"images/loaderbar-sheet0.png",
		"images/gameoverbg-sheet0.png",
		"images/gameovertitle-sheet0.png",
		"images/restartbutton-sheet0.png",
		"images/sprite-sheet0.png",
		"images/treasure-sheet0.png",
		"images/homescreen-sheet0.png",
		"images/homescreentitle-sheet0.png",
		"images/startbutton-sheet0.png",
		"media/scream-sfx-cartoon.ogg",
		"media/wilhelm-scream-sound-effect.ogg",
		"media/game scream.ogg",
		"media/bgm.ogg",
		"media/bgm ran.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}