{
	"version": 1708226196,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/background-sheet0.png",
		"images/tiledbackground.png",
		"images/tile-sheet0.png",
		"images/tile-sheet1.png",
		"images/tile2-sheet0.png",
		"images/tile2-sheet1.png",
		"images/player-sheet0.png",
		"images/duri-sheet0.png",
		"images/enemywalking_-sheet0.png",
		"images/enemywalking_-sheet1.png",
		"images/koin-sheet0.png",
		"images/nyawa-sheet0.png",
		"images/key2-sheet0.png",
		"images/bawah-sheet0.png",
		"images/finish-sheet0.png",
		"images/papan-sheet0.png",
		"images/level-sheet0.png",
		"images/play-sheet0.png",
		"images/level2-sheet0.png",
		"images/gameover-sheet0.png",
		"images/button_2-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/pop-sheet0.png",
		"images/tile6-sheet0.png",
		"images/tile7-sheet0.png",
		"images/tile8-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/tree-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite5-sheet1.png",
		"images/signarrow-sheet0.png",
		"images/bush-sheet0.png",
		"images/kaktus-sheet0.png",
		"images/sign-sheet0.png",
		"images/stoneblock-sheet0.png",
		"images/crate-sheet0.png",
		"images/cactus-sheet0.png",
		"images/stone-sheet0.png",
		"images/grass-sheet0.png",
		"images/grass2-sheet0.png",
		"images/exit-sheet0.png",
		"media/click.m4a",
		"media/click.ogg",
		"media/collect gem.m4a",
		"media/collect gem.ogg",
		"media/enemyhit.m4a",
		"media/enemyhit.ogg",
		"media/jingle lose.m4a",
		"media/jingle lose.ogg",
		"media/jingle win.m4a",
		"media/jingle win.ogg",
		"media/mattoglseby - 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}